### ISSUE TITLE
Consider caching version comparisons or do them once in `__init__`

### ISSUE THREAD

**Issue by bdraco** [DCSBL/python-homewizard-energy#206]
https://github.com/DCSBL/python-homewizard-energy/blob/0de2bffdcb23aef8bb86261e61cb3fe90834acf3/homewizard_energy/features.py#L38

![versions](https://user-images.githubusercontent.com/663432/229600400-3d50b523-a2f6-4a2e-9d5e-68f2277de0ae.png)

**Comment by DCSBL** [comment]
Great suggestion!

I have no idea what I am looking at, but caching sounds nice.

**Comment by bdraco** [comment]
Its a callgrind file rendered in qcachegrind from https://www.home-assistant.io/integrations/profiler/#service-profilerstart
