### ISSUE TITLE
Version missing

### ISSUE THREAD

**Issue by fabaff** [DCSBL/python-homewizard-energy#28]
The [`version` entry](https://github.com/DCSBL/python-homewizard-energy/blob/main/pyproject.toml#L3) in `pyproject.toml` is not set. The tag for [1.0.1](https://github.com/DCSBL/python-homewizard-energy/blob/v1.0.1/pyproject.toml#L3) contains `0.0.0` instead of `1.0.1`.

When using `main`, it's hard to tell which state is actually installed.

```bash
$ poetry install
Creating virtualenv python-homewizard-energy-xoLeU06e-py3.10 in /home/test/.cache/pypoetry/virtualenvs
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

Package operations: 78 installs, 0 updates, 0 removals

  • Installing pyparsing (3.0.7)
[...]
  • Installing vulture (2.3)
  • Installing yamllint (1.26.3)

Installing the current project: python-homewizard-energy (0.0.0)
```

Looks like that one of the workflows is not working properly.

**Comment by DCSBL** [comment]
Thanks for the heads-up!

My workflow is that the `release.yml` updates the version just before uploading the files to pypi based on the latest tag. I use `git describe` if I need to know the latest version while working on the files via Git.

I don't like the idea of (semi)manually change the version in `pyproject.toml`, because that could result (and have been resulted) in a version mismatch.

I'm open for suggestions 👍

**Comment by fabaff** [comment]
> I use git describe if I need to know the latest version while working on the files via Git.

`main` is "post-release" and not vX.X.X. But I guess that depends on the point of view :wink: 

> I don't like the idea of (semi)manually change the version in pyproject.toml, because that could result (and have been resulted) in a version mismatch.

`pyproject.toml` for the tags has currently a version mismatch because there is no version set. Thus, most tools (e.g., `pip`) are unable to determine the actual release as it is [`version = "0.0.0"`](https://github.com/DCSBL/python-homewizard-energy/blob/v1.0.1/pyproject.toml#L3) and not 1.0.1 for the latest release while using the GitHub sources.

https://github.com/home-assistant/core/pull/67973 will introduce this module to Home Assistant. Home Assistant will get the source from PyPI. No issue there as `release.yml` will set the `version`. 

All distributions which are shipping Home Assistant (e.g., NixOS, Gentoo or Arch) will have to ship `python-homewizard-energy` as well. Most distributions prefer to use the GitHub releases (if they are available) because they want to run the test suite (often excluded in the PyPI source among other things like the `LICENSE` or the `README` files). At the moment they would have to patch `pyproject.toml`. No big deal, though, but unexpected.

> I'm open for suggestions +1

Use the same workflow approach as for https://github.com/DCSBL/aiohwenergy. There, the version is set.

**Comment by DCSBL** [comment]
The version is set just before uploading in the workflow container. So when you install the package via pip you get the correct version.
```
$ pip install python-homewizard-energy
Installing collected packages: python-homewizard-energy
Successfully installed python-homewizard-energy-1.0.1

$ pip show python-homewizard-energy
Name: python-homewizard-energy
Version: 1.0.1
Summary: Asynchronous Python client for the HomeWizard Energy
Home-page: https://github.com/dcsbl/python-homewizard-energy
Author: DCSBL
Author-email: 
License: Apache-2.0
Location: ~/.pyenv/versions/3.9.4/lib/python3.9/site-packages
Requires: aiohttp
Required-by: 
```

> Most distributions prefer to use the GitHub releases

Seems legit. Better have a uniform way of building. I will see if I can automatically set the version based on the tag but will do it manually for now.
